development:
  adapter: postgresql
  database: my_database_development
  username: postgres
  password: harisa
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: my_database_test
  username: postgres
  password: harisa
  pool: 5
  timeout: 5000

  production:
    adapter: postgresql
    database: db/production.sqlite3